steps:
  # 1️⃣ Install dependencies
  - name: node:20
    entrypoint: npm
    args: ["install"]

  # 2️⃣ Build with secrets injected
  - name: node:20
    entrypoint: npm
    args: ["run", "build"]
    secretEnv:
      - VITE_API_BASE_URL
      - VITE_FORWARD_PROXY_URL
      - VITE_LAYER8_BASE_URL

  # 3️⃣ Ensure GCS bucket exists for l8.globeandcitizen.com
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    id: "create-bucket"
    entrypoint: bash
    args:
      - -c
      - |
        if ! gsutil ls -b gs://l8.globeandcitizen.com >/dev/null 2>&1; then
          echo "Creating bucket gs://l8.globeandcitizen.com"
          gsutil mb -p $PROJECT_ID -l us-central1 gs://l8.globeandcitizen.com
          gsutil web set -m index.html -e index.html gs://l8.globeandcitizen.com
          gsutil iam ch allUsers:objectViewer gs://l8.globeandcitizen.com
        else
          echo "Bucket already exists."
        fi

  # 4️⃣ Sync build output to the new bucket
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gsutil
    args: ["-m", "rsync", "-r", "dist/", "gs://l8.globeandcitizen.com"]

availableSecrets:
  secretManager:
    - versionName: projects/gc-now-471214/secrets/_VITE_API_BASE_URL_L8/versions/latest
      env: VITE_API_BASE_URL
    - versionName: projects/gc-now-471214/secrets/_VITE_FORWARD_PROXY_URL/versions/latest
      env: VITE_FORWARD_PROXY_URL
    - versionName: projects/gc-now-471214/secrets/_VITE_LAYER8_BASE_URL_PROD/versions/latest
      env: VITE_LAYER8_BASE_URL_PROD

options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
