steps:
  # 1️⃣ Install dependencies
  - name: node:20
    entrypoint: npm
    args: ["install"]

  # 2️⃣ Build with secrets injected
  - name: node:20
    entrypoint: npm
    args: ["run", "build"]
    secretEnv:
      - VITE_API_BASE_URL
      - VITE_FORWARD_PROXY_URL
      - VITE_LAYER8_BASE_URL_PROD

  # 3️⃣ Sync build output to the verified bucket
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gsutil
    args: ["-m", "rsync", "-r", "dist/", "gs://l8.globeandcitizen.com"]

availableSecrets:
  secretManager:
    - versionName: projects/gc-now-471214/secrets/_VITE_API_BASE_URL_L8/versions/latest
      env: VITE_API_BASE_URL
    - versionName: projects/gc-now-471214/secrets/_VITE_FORWARD_PROXY_URL/versions/latest
      env: VITE_FORWARD_PROXY_URL
    - versionName: projects/gc-now-471214/secrets/_VITE_LAYER8_BASE_URL_PROD/versions/latest
      env: VITE_LAYER8_BASE_URL_PROD

options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
