steps:
  - name: "node:18"
    entrypoint: "npm"
    args: ["i"]

  # Build the application with environment variables
  - name: "node:18"
    entrypoint: "npm"
    args: ["run", "build"]
    env:
      - "NODE_ENV=production"
    secretEnv:
      [
        "VITE_API_BASE_URL",
        "VITE_FORWARD_PROXY_URL",
        "VITE_LAYER8_BASE_URL_PROD",
        "VITE_LAYER8_BASE_URL_DEV",
      ]

  # Sync to bucket with delete flag to remove old files
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "gsutil"
    args: [
        "-m",
        "rsync",
        "-r",
        "-d", # -d flag removes files that don't exist locally
        "dist/",
        "gs://globeandcitizen.com",
      ]

  # Set proper cache headers and content types for optimization
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        # Set cache headers for static assets (1 year cache)
        gsutil -m setmeta -h "Cache-Control:public,max-age=31536000,immutable" \
          'gs://globeandcitizen.com/css/**' \
          'gs://globeandcitizen.com/js/**' \
          'gs://globeandcitizen.com/img/**' \
          'gs://globeandcitizen.com/fonts/**' 2>/dev/null || true

        # HTML files should not be cached (for SPA updates)
        gsutil -m setmeta -h "Cache-Control:no-cache,no-store,must-revalidate" \
          'gs://globeandcitizen.com/*.html' 2>/dev/null || true

        # Set proper content types
        gsutil -m setmeta -h "Content-Type:application/javascript" \
          'gs://globeandcitizen.com/js/*.js' 2>/dev/null || true
        gsutil -m setmeta -h "Content-Type:text/css" \
          'gs://globeandcitizen.com/css/*.css' 2>/dev/null || true

  # Configure bucket for website hosting
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "gsutil"
    args:
      [
        "web",
        "set",
        "-m",
        "index.html",
        "-e",
        "index.html",
        "gs://globeandcitizen.com",
      ]

# Use Secret Manager for environment variables
availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/vite-api-base-url/versions/latest
      env: "VITE_API_BASE_URL"
    - versionName: projects/$PROJECT_ID/secrets/vite-forward-proxy-url/versions/latest
      env: "VITE_FORWARD_PROXY_URL"
    - versionName: projects/$PROJECT_ID/secrets/vite-layer8-base-url-prod/versions/latest
      env: "VITE_LAYER8_BASE_URL_PROD"
    - versionName: projects/$PROJECT_ID/secrets/vite-layer8-base-url-dev/versions/latest
      env: "VITE_LAYER8_BASE_URL_DEV"

options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
  machineType: "E2_HIGHCPU_8" # Faster builds

timeout: "1200s"
